### ISSUE TITLE
How can I export my database or get the file path?

### ISSUE THREAD

**Issue by minhchienwikipedia** [margelo/react-native-nitro-sqlite#4]
I want to export my database or get my database file path. How can I do it?

**Comment by pbbadenhorst** [comment]
See the part of docs: [Loading existing DBs](https://github.com/margelo/react-native-quick-sqlite#loading-existing-dbs)

For more information

**Comment by minhchienwikipedia** [comment]
I found it, just using `react-native-fs` and get `RNFS.readDir(RNFS.DocumentDirectoryPath)`, the file should be in there
