### ISSUE TITLE
build fails on android with little explanation as to why :/

### ISSUE THREAD

**Issue by valn1** [margelo/react-native-nitro-sqlite#46]
First of all, thank you Marc for this lib and your other libs as well, they are some of the best maintained libs for react-native and very well made and easy to use.

i started using this lib for persisting data from my backend today and needed to patch it as it was breaking asking for minsdk=23 even though i am already using it. After patching, it was working fine, but then, I installed another lib and tried rebuilding the app to no avail.
I then tried gradlew clean and rm -rf node_modules and yarn.lock, but it didn't work either.
removing the new lib did nothing.

thanks in advance.

![image](https://github.com/margelo/react-native-quick-sqlite/assets/40465512/1c791e40-d096-4f0b-8a8d-010ed8ebbfb1)

**Comment by valn1** [comment]
in case you need to reproduce the error:
https://github.com/valn1/pesagem

**Comment by valn1** [comment]
I found a way around it while it does not get fixed
you gotta remove any patch made to the lib, clean and rerun the project, it will complain about the minsdkversion.
then, you change it to 23 in the lib's android/build.gradle file and run again.
it will show a ton of warnings  but will run

**Comment by Hubi1234** [comment]
> I found a way around it while it does not get fixed you gotta remove any patch made to the lib, clean and rerun the project, it will complain about the minsdkversion. then, you change it to 23 in the lib's android/build.gradle file and run again. it will show a ton of warnings but will run

This helped! Thanks! For some reason you need to build it first with minsdk 21 change it to 23 and build again. So applying a patch after npm install will not work. This applies for me at RN v74.5 with quick-sqlite  8.1.0

**Comment by chrispader** [comment]
As this is not related to the library implementation, i think we can close this. Lmk if there are any more issues :)
