### ISSUE TITLE
Apk build failed

### ISSUE THREAD

**Issue by wogno** [margelo/react-native-nitro-sqlite#47]
When I want to build apk I get this error when I go on error message I see this line that is origin of issue
<img width="1026" alt="Capture d’écran 2024-06-15 à 08 27 34" src="https://github.com/margelo/react-native-quick-sqlite/assets/31076843/2ac4edb8-459d-4582-a15d-391472cf71c6">

![image](https://github.com/margelo/react-native-quick-sqlite/assets/31076843/0e238d82-1415-4c8d-a9e4-4d86fc9a336e)

**Comment by wogno** [comment]
If some can help me

**Comment by valn1** [comment]
@wogno can you show more info about your project and what you tried to do?
information like versions of the libs, your build.gradle sdk versions, your OS, what command you ran, etc.
i am running the latest versions for react-native and quick-sqlite and the apk built just fine on my machine

**Comment by valn1** [comment]
i can tell it is not the latest version as the android/build.gradle file on my project only has 126 lines

**Comment by wogno** [comment]
My react native
"react-native": "0.72.3",
"react-native-quick-sqlite": "^7.0.0"

Work fine on  IOS, but for not on android
./gradlew assembleRelease and clean before

Even to lunch app on local device or emulator not work, with yarn android

<img width="765" alt="Capture d’écran 2024-06-17 à 14 51 42" src="https://github.com/margelo/react-native-quick-sqlite/assets/31076843/1c6e685f-7c99-4668-92f1-5dd32173b31a">

**Comment by wogno** [comment]
<img width="857" alt="Capture d’écran 2024-06-17 à 17 22 18" src="https://github.com/margelo/react-native-quick-sqlite/assets/31076843/2cbc967a-c818-46e2-a5fc-23d14b1c05f9">

**Comment by wogno** [comment]
> When I want to build apk I get this error when I go on error message I see this line that is origin of issue

This not app gradle, it's quick-sqlite gradle

**Comment by valn1** [comment]
try upgrading to v8

**Comment by wogno** [comment]
Thanks move v8 and work well, thanks

**Comment by wogno** [comment]
v8 version work well with react native 0.72
